### ISSUE TITLE
get_max_container_depth_or_default: limit to max

### ISSUE THREAD

**Issue by rurban** [kstenerud/concise-encoding#2]
https://github.com/kstenerud/concise-encoding/blob/c0d5fcb62d2d81b77bce2f123f5e34c045a2a34e/reference-implementation/cbe/src/cbe_internal.h#L90

if the get_max_container_depth_or_default arg is larger than the hardcoded 500, a wrong and security relevant size is returned.
it should check against arg < CBE_DEFAULT_MAX_CONTAINER_DEPTH also.

**Comment by kstenerud** [comment]
I'm not quite sure I follow... `get_max_container_depth_or_default()` takes the "max" value passed in, and either returns that value if it is greater than 0, or returns the default if it's <= 0. This is to implement the behavior described [here](https://github.com/kstenerud/concise-encoding/blob/c0d5fcb62d2d81b77bce2f123f5e34c045a2a34e/reference-implementation/cbe/include/cbe/cbe.h#L335) and [here](https://github.com/kstenerud/concise-encoding/blob/c0d5fcb62d2d81b77bce2f123f5e34c045a2a34e/reference-implementation/cbe/include/cbe/cbe.h#L377)

The name's not the best, but I couldn't really think of something better.

**Comment by rurban** [comment]
The problem is that the user can add a max_container_depth larger than the hard limit, which is dependent on the stack size. With debugging it's usually 100-500, with full optimizations sometimes ~10000-50000. In my case for such an encoder I probe the hard limit for the max_container_depth in configure (via binary search), and set the max_container_depth. The soft limit should be configurable at run-time via that get_max_container_depth_or_default(). Because the call could be from inside some nested functions already, hence the limit must be lower in some cases than the hard limit.
The name is bad, I called it hard and soft limit. set_max_container_depth_soft_limit().

**Comment by kstenerud** [comment]
I think there may be a misunderstanding here. max container depth is simply a limit to how deeply the encoder and decoder will allow `map begin` and `list begin` before returning an error. The stack has nothing to do with it, since the CBE library algorithms are not recursive. 500 was just a number I picked at random for people who don't care, since it's unlikely that you'd encounter a document with such a container depth under normal conditions, and 500 wouldn't cause a crippling drain on resources.

But really, there's nothing stopping you from accepting a document with a container depth of a million or a billion (other than the RAM requirements to represent the document in memory). There's no hard technical limit in the library itself to how deep you can go; it's only a tool to help keep things "reasonable" for your particular use case, and to help guard against abusive documents that take crazy amounts of resources to load.

If your particular use case does require a particular hard limit (due to recursion or some other resource limitation), then you should be wrapping this library to accept only a particular max depth range (for example, 1-300) rather than exposing it to the user directly.

**Comment by rurban** [comment]
I see, so there's no hard limit based on a stack size limitation. sorry for the confusion.
