### ISSUE TITLE
Identifier length

### ISSUE THREAD

**Issue by kengruven** [kstenerud/concise-encoding#23]
Nitpicking: the CBE spec says identifier length can have value "0-127".  The CE spec says identifiers have a minimum length of 1, so 0 would not actually be allowed here.

**Comment by kstenerud** [comment]
Fixed here: https://github.com/kstenerud/concise-encoding/commit/97cf016df829570dafc69260edb644a43f99bace

Feel free to submit anal or nit-picky issues to your heart's content! The stricter we are in the early stages, the longer we're protected against the need to release a version 2 in order to fix the problems with version 1 ;-)

**Comment by kengruven** [comment]
Oh, I meant 5 lines below that:

```
| Length       |   7  | 0-127             |
```

**Comment by kstenerud** [comment]
Whoops! https://github.com/kstenerud/concise-encoding/commit/5cfd40a01957e0b4d1ed99401717ba697c1b7733
