### ISSUE TITLE
What's the reasoning behind array types  cb and u8x  being separate?

### ISSUE THREAD

**Issue by ST92** [kstenerud/concise-encoding#40]
I can't see how the separation of those types is useful.

**Comment by kstenerud** [comment]
It's mainly about signalling the intent and structure of the data.

- `u8x` is simply an array of values in the range 0-255, with no inherent structure other than the individual element values (like all array types). It's for sending large series of simple data in an efficient manner. For example you might send a series of integer percentage values ranging from 0-100. Any decoder can take in this data because it is exactly what it is: a series of integers.
- `cb` and `ct` signal that the contents of this object are not simply array elements, but have special structure and meaning that goes beyond the capabilities of the Concise Encoding format. The receiving end would use this signalling information to call some special process to decode this complex type. If it cannot understand the type or lacks any custom type decoding at all, it can either ignore it or raise an issue about it (depending on how important the data is for the receiver).

**Comment by ST92** [comment]
Thank you for clarifying
