### ISSUE TITLE
String syntax

### ISSUE THREAD

**Issue by svenssonaxel** [kstenerud/concise-encoding#7]
There are several potential issues with the string encoding. I'll get back with details, just wanted to leave this as a placeholder/headsup.

**Comment by svenssonaxel** [comment]
OK, finally got around to it. This is only about CTE for now.

Problem 1:
There are three separate string encodings.
This is quite complex.
If there are desired features that cannot be concurrently supported by one encoding, then at the very least limit it to two.

Problem 2:
[Escaping escaping](https://axelsvensson.com/escaping-escaping) is not supported.
An example of a string that cannot be written with minimal escaping is `"a\"\n\\\27fb"` or in other words, letter `a`, double-quote, newline, backslash, DEL, letter `b`.
Since it contains a double-quote, a newline, a backslash and a control character, it cannot be encoded as an unquoted string.
The double-quote and backslash must be escaped if encoded as a quoted sequence, even though this need is artificial.
Since the string contains a control character, it cannot be encoded as a verbatim string (or "verbatim sequence"?) at all.

Problem 1 and 2 could be solved with one and the same change:
Replace quoted and verbatim strings with one encoding that supports both use cases, and also supports escaping escaping.
An example encoding could be composed as:

 * Optionally, an escape identifier, composed of:
   * A backslash
   * A sequence of zero or more printable, non-whitespace characters (in accordance with human editability).
 * A double-quote.
 * The string contents, except escaping can occur using the designated escape identifier.
 * The escape identifier followed by a double-quote.

Note that you'd have to remove double-quote from the escape sequence table.
In this example encoding, the example string above could be encoded in either of the following ways:

 * backslash, underscore, double-quote, letter `a`, double-quote, newline, backslash, backslash, underscore, sequence `27f`, letter `b`, backslash, underscore, double-quote.
 * backslash, letter `e`, double-quote, letter `a`, double-quote, newline, backslash, backslash, letter `e`, sequence `27f`, letter `b`, backslash, letter `e`, double-quote.

For strings that do not contain control characters or double-quote, this encoding is particularly simple as it reduces to a verbatim encoding with just double-quotes around it.
For people who do not care to learn the full spec, it is probably sufficient to learn to begin and end a string with backslash and double-quote, in order to be able to use escaping inside the string.
I'm sure you could find ways to improve on this example encoding, but at least problems 1 and 2 above are solved.
For example, I suspect that replacing the double-quote with a single-quote, and replacing the backslash also with a single-quote, could beautify the encoding a bit, although it would require a three characters rather than two to delimit strings that contain the respective quote character.

Problem 3:
The specification for unquoted string is imprecise.
Especially, the "LOOK similar" condition must be specified exactly.
Perhaps it'd be better to begin with a narrow definition and expand from there, e.g. `[a-zA-Z0-9_.:-]+`.
At the very least, put a "todo" note there.
Unless the same goes for "Human editability", specify that those are just guidelines and not part of the actual spec.

**Comment by kstenerud** [comment]
Hi Axel,

Thanks for that! This has me thinking now...

I'm not sure if I've fully understood all of your concerns, so I'll put down how I've understood it, and my comments:

1. **Multiple string encoding methods complicates things.** I heartily agree. Having only one (simple) quoted encoding method would be best.
2. **Escaping escaping is not supported.** I'm not sure if I understand this. The purpose of verbatim sequences was to handle this sort of thing since they behave like Bash here documents.
3. **Since the string contains a control character, it cannot be encoded as a verbatim string (or "verbatim sequence"?) at all.** This is also true of Bash here documents and similar in Python as well (or at least true in spirit). If you put bare u+007f or other invisible control characters in a text document, humans can't edit the document anymore without risking data loss from their editor's text handling. So these characters should always be escaped in order to keep the document safely editable in the many user's editors of choice.

Control characters CR, LF, TAB can technically be encoded by themselves in a quoted string, and can be (somewhat safely) edited in a text editor:

```
"A string with newline followed by tab
	and hopefully your editor won't replace the tab with spaces and LF with CRLF!"
```

But for the other things we'd still have a problem. There should be some way to allow both quoted and verbatim text to be represented in the same encoding method... Maybe I could replace verbatim strings with a "here document" escape sequence that uses a similar mechanism - something like `\.` + [end-identifier] + [single-whitespace] + [your-contents] + [end-identifier]:
```
"blah blah \.XX verbatim text with \ and " characters and
newlineXX and then the end of the quoted string"
```

Or, using newline for the whitespace separator:
```
"blah blah \.XX
verbatim text with \ and " characters and
newlineXX and then the end of the quoted string"
```

Both of which would decode to:
```
blah blah verbatim text with \ and " characters and
newline and then the end of the quoted string
```

This would eliminate the verbatim string type entirely. Technically, there's nothing stopping someone from encoding u+007f in a verbatim sequence, except for the human editability rule.

**Comment by svenssonaxel** [comment]
Let's leave HERE documents aside, they have their own problems whatever their purpose was.

Consider this design goal: It should be possible to encode strings in such a way that every character that is allowed in the document at all (e.g. is printable) is represented by itself. This is what I mean by supporting "escaping escaping".

If you subscribe to this design goal, consider a string that begins with a double-quote.
Such a string can not be unquoted, and if you use quoted sequence, the double-quote is represented by backslash and double-quote, not by itself.
So, the only option (in order to prove that the design goal is fulfilled for such a string) is to use verbatim encoding.

Now, consider a string that includes a control character.
This character has to be escaped, by necessity.
Since escaping is not allowed in unquoted strings and neither in verbatim strings (IIUC), the only option is to use a quoted sequence.

Now, consider a string that both begins with a double-quote and contains a control character.
Then, we have no option to encode it in a way that proves that the design goal is fulfilled.
Therefore, the combination of these three encodings does not fulfill the design goal.

The example encoding I proposed does however, standing by itself, fulfill this design goal.
It does this by letting the user choose an escape sequence ad-hoc that is used both for escaping and for end-of-string.
For example:
```
\-"blah blah verbatim text with \ and " characters and
newline and then the end of the quoted string\-"
```

**Comment by kstenerud** [comment]
I think we're misunderstanding each other... What I proposed is exactly that the user can specify their own end sequence. The verbatim escape sequence from earlier:

```
"\.XX text with " in itXX"
```
can also be encoded as

```
"\.END text with " in itEND"
```
or
```
"\.@ text with " in it@"
```
The end sequence is user-definable.

Since the verbatim sequence is itself an escape sequence, it can coexist with other escape sequences:

```
"SOH=\201, BEL=\207, \.## and some """"""" in a verbatim sequence##, and now newline\nand a doggie: \51f415"
```
Which decodes to:
```
SOH=, BEL=, and some """"""" in a verbatim sequence, and now newline
and a doggie: 🐕
```

**Comment by svenssonaxel** [comment]
Right, I agree that allowing verbatim substrings inside quoted strings as per your comment 2 above, would support escaping escaping. I just tried to clarify how the CTE specification currently doesn't.

**Comment by kstenerud** [comment]
Ok cool! I've updated the spec. Escape sequences are now uniform across all contexts where they're allowed: https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#escape-sequences

The verbatim sequence is now just another escape sequence: https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#verbatim-sequence
